### ISSUE TITLE
Only random splitting?

### ISSUE THREAD

**Issue by Dinxin** [tencent-ailab/grover#4]
![image](https://user-images.githubusercontent.com/19572535/111759208-537dd100-88d8-11eb-9e00-ec848fc6412a.png)
However, the paper claimed that the validation of the model adopts commonly-used scaffold splitting?

**Comment by idontkonwher** [comment]
Do you know the specific implementation?  I have the same question.

**Comment by yuning-you** [comment]
Any update on this? I have the same question.
